version: '3.8'

services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
      NODE_ENV: test
    depends_on:
      test-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  test-runner:
    build: .
    environment:
      TEST_BASE_URL: http://api:3000
      TEST_DATABASE_URL: postgresql://testuser:testpass@test-db:5432/testdb
    depends_on:
      api:
        condition: service_healthy
      test-db:
        condition: service_healthy
    command: bun test
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src

volumes:
  test_postgres_data: